In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\Advanced_Multi-Source_Data_Pipeline\\Scraped_crypto(1).csv")
df

,Unnamed: 0,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,78634.000000,1579089652770,1,1579090360482,2.838799e+10,...,2.008138e+07,2.100000e+07,126080.000000,-37.63171,2025-10-06T10:57:42.000Z,67.810000,1.158638e+05,2013-07-05T16:00:00.000Z,NaN,2026-09-08T10:46:30.000Z
1,1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2483.720000,303085220706,2,303085220706,1.078036e+10,...,1.220297e+08,NaN,4946.050000,-49.78373,2025-08-24T11:21:03.000Z,0.432979,5.735357e+05,2015-10-19T16:00:00.000Z,"{'times': 41.22744770600797, 'currency': 'btc'...",2026-09-08T10:46:30.000Z
2,2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999612,183369701757,3,188834594823,5.236984e+10,...,1.889055e+11,NaN,1.320000,-24.44896,2018-07-23T16:00:00.000Z,0.572521,7.459836e+01,2015-03-01T16:00:00.000Z,NaN,2026-09-08T10:46:30.000Z
3,3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,757.330000,100841624829,4,100841628010,1.107447e+09,...,1.331615e+08,2.000000e+08,1369.990000,-44.72041,2025-10-13T00:41:24.000Z,0.039818,1.901883e+06,2017-10-18T16:00:00.000Z,NaN,2026-09-08T10:46:30.000Z
4,4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.400000,87754936306,5,139840650751,1.896142e+09,...,9.998563e+10,1.000000e+11,3.650000,-61.64502,2025-07-17T19:40:53.000Z,0.002686,5.196478e+04,2014-05-21T16:00:00.000Z,NaN,2026-09-08T10:46:30.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,injective-protocol,inj,Injective,https://coin-images.coingecko.com/coins/images...,6.250000,624512089,95,624512089,2.333809e+08,...,1.000000e+08,NaN,52.620000,-88.13089,2024-03-14T07:06:22.000Z,0.657401,8.500454e+02,2020-11-03T08:19:30.000Z,NaN,2026-09-08T10:46:30.000Z
96,96,official-trump,trump,Official Trump,https://coin-images.coingecko.com/coins/images...,2.270000,619265191,96,2267231895,1.876301e+08,...,1.000000e+09,1.000000e+09,73.430000,-96.91194,2025-01-19T03:50:34.000Z,1.370000,6.548837e+01,2026-08-13T18:40:30.000Z,NaN,2026-09-08T10:46:30.000Z
97,97,beldex,bdx,Beldex,https://coin-images.coingecko.com/coins/images...,0.077710,611626584,97,772405069,1.099994e+07,...,9.939509e+09,NaN,0.450785,-82.76120,2018-12-16T16:00:00.000Z,0.000275,2.813909e+04,2019-11-01T03:05:12.000Z,"{'times': -0.6894284115450982, 'currency': 'us...",2026-09-08T10:46:30.000Z
98,98,xdce-crowd-sale,xdc,XDC Network,https://coin-images.coingecko.com/coins/images...,0.028983,578165056,98,1103353562,7.305587e+06,...,3.806569e+10,NaN,0.192754,-84.96358,2021-08-20T20:39:48.000Z,0.000395,7.231643e+03,2019-07-21T16:00:00.000Z,"{'times': 0.5529974415539096, 'currency': 'eth...",2026-09-08T10:46:30.000Z
99,99,ether-fi,ethfi,Ether.fi,https://coin-images.coingecko.com/coins/images...,0.592432,571926334,99,571926334,5.618779e+07,...,9.653500e+08,1.000000e+09,8.530000,-93.05383,2024-03-27T15:14:46.000Z,0.266530,1.222760e+02,2026-06-05T19:19:15.000Z,NaN,2026-09-08T10:46:30.000Z

In [3]:
# standardising the column name

df.columns=df.columns.str.strip().str.title()

In [4]:
# ID column

# column values into title case
df["Id"]=df["Id"].str.strip().str.title()
df["Id"].isnull().sum()
df["Id"].duplicated().sum()
df["Id"].unique()

<StringArray>
[                                                     'Bitcoin',
                                                     'Ethereum',
                                                       'Tether',
                                                  'Binancecoin',
                                                       'Ripple',
                                                     'Usd-Coin',
                                                       'Solana',
                                                         'Tron',
                                                 'Figure-Heloc',
                                                        'Zcash',
                                                  'Hyperliquid',
                                                     'Dogecoin',
                                                         'Rain',
                                                         'Usds',
                                                       'Monero',
                                                    'Chainlink',
                                                     'Whitebit',
                                                    'Leo-Token',
                                                      'Cardano',
                                                      'Stellar',
                                                 'Bitcoin-Cash',
                                                          'Dai',
                                                  'Ethena-Usde',
                                                      'Uniswap',
                                                     'Litecoin',
                                                    'Usd1-Wlfi',
                                               'Canton-Network',
                                             'The-Open-Network',
                                             'Hedera-Hashgraph',
                                                  'Avalanche-2',
                                                          'Sui',
                                                'Global-Dollar',
                                                    'Shiba-Inu',
                                                         'Near',
                                                   'Paypal-Usd',
                                             'Crypto-Com-Chain',
           'Blackrock-Usd-Institutional-Digital-Liquidity-Fund',
                                                  'Tether-Gold',
                                                     'Memecore',
                                                'Hashnote-Usyc',
                                                    'Bittensor',
                                                   'Ripple-Usd',
                                                          'Okb',
                                         'Ondo-Us-Dollar-Yield',
                                                       'Mantle',
                                                      'Aster-2',
                                                         'Aave',
                                                     'Pax-Gold',
                                                 'Ondo-Finance',
                                                     'Polkadot',
                                      'World-Liberty-Financial',
                                                'Worldcoin-Wld',
                                                     'Pump-Fun',
                                            'Internet-Computer',
                                                       'Morpho',
                                                       'Ethena',
                                                          'Sky',
                                                         'Pepe',
                                                      'Htx-Dao',
                                                         'Usdd',
                                                 'Bitget-Token',
                                                        'Usdgo',
                                               'Falcon-Finance',
                                                        'Bfusd',
                                             'Ethereum-Classic',
                                               'United-Stables',
                         'Spiko-Amundi-Overnight-Swap-Fund-Eur',
                                                       'Bitway',
                                                      'Lighter',
                                                     'Arbitrum',
                                                   'Pi-Network',
                                      'Polygon-Ecosystem-Token',
                                              'Gatechain-Token',
                                                'Quant-Network',
                                           'Blockchain-Capital',
                                                        'Kaspa',
                                                'Kucoin-Shares',
                                                        'Eutbl',
                                                       'Cosmos',
                                                     'Algorand',
                                                 'Venice-Token',
                                                         'Just',
                                                         'Nexo',
                                      'Jupiter-Exchange-Solana',
                                                         'Dash',
                         'Janus-Henderson-Anemoy-Treasury-Fund',
                                                 'Render-Token',
 'Superstate-Short-Duration-Us-Government-Securities-Fund-Ustb',
                                                     'Stable-2',
                                            'Pancakeswap-Token',
                          'Janus-Henderson-Anemoy-Aaa-Clo-Fund',
                                                     'Filecoin',
                                                          'Gho',
                                                      'Vechain',
                                            'Aerodrome-Finance',
                                           'Injective-Protocol',
                                               'Official-Trump',
                                                       'Beldex',
                                              'Xdce-Crowd-Sale',
                                                     'Ether-Fi']
Length: 100, dtype: str

In [5]:
# symbol column

df["Symbol"]=df["Symbol"].str.strip().str.title().astype("string")
df["Symbol"].isnull().sum()
df["Symbol"].duplicated().sum()

np.int64(0)

In [6]:
# name column
df["Name"]=df["Name"].str.strip().str.title()
df["Name"].isnull().sum()
df["Name"].duplicated().sum()

np.int64(0)

In [7]:
# Image column
df["Image"]=df["Image"].str.split()
df["Image"].isnull().sum()
df["Image"].duplicated().sum()

np.int64(0)

In [8]:
# current price column
df["Current_Price"].isnull().sum()
df["Current_Price"].duplicated().sum()
df["Current_Price"].value_counts()

print("zero values=",(df["Current_Price"]==0).sum())

print("Negative values: ",(df["Current_Price"]< 0).sum())

zero values= 0
Negative values:  0

In [9]:
# market cap columnn\

df["Market_Cap"].isnull().sum()
df["Market_Cap"].duplicated().sum()
df["Market_Cap"].value_counts()
df["Market_Cap"].dtype

print("Zero value: ",(df["Market_Cap"]==0).sum())
print("negative value: ",(df["Market_Cap"]<0).sum())

Zero value:  0
negative value:  0

In [10]:
# Market_Cap_Rank column
print(df["Market_Cap_Rank"].isna().sum())

df["Market_Cap_Rank"].duplicated().sum()

print("Zero value: ",(df["Market_Cap_Rank"]==0).sum())

print("-ve value: ",(df["Market_Cap_Rank"]<0).sum())

0
Zero value:  0
-ve value:  0

In [11]:
# Fully_Diluted_Valuation column

df["Fully_Diluted_Valuation"].isnull().sum()

df["Fully_Diluted_Valuation"].duplicated().sum()

print("Zero Value: ",(df["Fully_Diluted_Valuation"]==0).sum())
# convert 0 into the nan values
df["Fully_Diluted_Valuation"]=df["Fully_Diluted_Valuation"].replace(0,np.nan)
df["Fully_Diluted_Valuation"]

print("negative Value: ",(df["Fully_Diluted_Valuation"]<0).sum())

# check the missing values
print("Missing values: ",df["Fully_Diluted_Valuation"].isna().sum())

Zero Value:  0
negative Value:  0
Missing values:  0

In [12]:
# Total_Volume column
df["Total_Volume"].isnull().sum()

df["Total_Volume"].duplicated().sum()

print("Zero Value: ",(df["Total_Volume"]==0).sum())
# check their percentage
print("zero_per:",(df['Total_Volume'] == 0).mean()*100)
print("-"*50)

# replace 0 eith nan
df["Total_Volume"]=df["Total_Volume"].replace(0,np.nan)
print(df["Total_Volume"])

df["Total_Volume"].dtype

Zero Value:  8
zero_per: 8.0
--------------------------------------------------
0     2.838799e+10
1     1.078036e+10
2     5.236984e+10
3     1.107447e+09
4     1.896142e+09
          ...
95    2.333809e+08
96    1.876301e+08
97    1.099994e+07
98    7.305587e+06
99    5.618779e+07
Name: Total_Volume, Length: 100, dtype: float64

dtype('float64')

In [13]:
# High_24H column
print("missing values  ",df["High_24H"].isnull().sum())
print("Duplicatedd    ",df["High_24H"].duplicated().sum())
print("Value counts  ",df["High_24H"].value_counts())

print("zero values=",(df["High_24H"]==0).sum())
df["High_24H"]=df["High_24H"].replace(0,np.nan)
print(df["High_24H"])
# fill missing values
df["High_24H"]=df["High_24H"].fillna(df["High_24H"].median())
print(df["High_24H"])

print("Negative values: ",(df["High_24H"]< 0).sum())

missing values   0
Duplicatedd     5
Value counts   High_24H
1.000000        6
79625.000000    1
2510.030000     1
0.999963        1
760.330000      1
               ..
6.690000        1
2.330000        1
0.079171        1
0.029772        1
0.604093        1
Name: count, Length: 95, dtype: int64
zero values= 1
0     79625.000000
1      2510.030000
2         0.999963
3       760.330000
4         1.410000
          ...
95        6.690000
96        2.330000
97        0.079171
98        0.029772
99        0.604093
Name: High_24H, Length: 100, dtype: float64
0     79625.000000
1      2510.030000
2         0.999963
3       760.330000
4         1.410000
          ...
95        6.690000
96        2.330000
97        0.079171
98        0.029772
99        0.604093
Name: High_24H, Length: 100, dtype: float64
Negative values:  0

In [14]:
# Low_24H column

print("missing values  ",df["Low_24H"].isnull().sum())
print("Duplicatedd    ",df["Low_24H"].duplicated().sum())
print("Value counts  ",df["Low_24H"].value_counts())

print("zero values=",(df["Low_24H"]==0).sum())
df["Low_24H"]=df["Low_24H"].replace(0,np.nan)
print(df["Low_24H"])
# fill missing values
df["Low_24H"]=df["Low_24H"].fillna(df["Low_24H"].median())
print(df["Low_24H"])

print("Negative values: ",(df["Low_24H"]< 0).sum())

missing values   0
Duplicatedd     3
Value counts   Low_24H
1.380000        2
1.000000        2
1.140000        2
78193.000000    1
2463.890000     1
               ..
5.600000        1
2.240000        1
0.077528        1
0.028802        1
0.571131        1
Name: count, Length: 97, dtype: int64
zero values= 1
0     78193.000000
1      2463.890000
2         0.999639
3       734.680000
4         1.380000
          ...
95        5.600000
96        2.240000
97        0.077528
98        0.028802
99        0.571131
Name: Low_24H, Length: 100, dtype: float64
0     78193.000000
1      2463.890000
2         0.999639
3       734.680000
4         1.380000
          ...
95        5.600000
96        2.240000
97        0.077528
98        0.028802
99        0.571131
Name: Low_24H, Length: 100, dtype: float64
Negative values:  0

In [15]:
# Price_Change_24H column

print("missing values  ",df["Price_Change_24H"].isnull().sum())
print("Duplicatedd    ",df["Price_Change_24H"].duplicated().sum())
print("Value counts  ",df["Price_Change_24H"].value_counts())

print("zero values=",(df["Price_Change_24H"]==0).sum())
df["Price_Change_24H"]=df["Price_Change_24H"].replace(0,np.nan)
print(df["Price_Change_24H"])
# fill missing values
df["Price_Change_24H"]=df["Price_Change_24H"].fillna(df["Price_Change_24H"].median())
print(df["Price_Change_24H"])

print("Negative values: ",(df["Price_Change_24H"]< 0).sum())

missing values   1
Duplicatedd     5
Value counts   Price_Change_24H
 0.000000      6
-779.436282    1
-6.871557      1
-0.000305      1
 13.020000     1
              ..
 0.553594      1
-0.011181      1
-0.000801      1
-0.000798      1
 0.002826      1
Name: count, Length: 94, dtype: int64
zero values= 6
0    -779.436282
1      -6.871557
2      -0.000305
3      13.020000
4      -0.002017
         ...
95      0.553594
96     -0.011181
97     -0.000801
98     -0.000798
99      0.002826
Name: Price_Change_24H, Length: 100, dtype: float64
0    -779.436282
1      -6.871557
2      -0.000305
3      13.020000
4      -0.002017
         ...
95      0.553594
96     -0.011181
97     -0.000801
98     -0.000798
99      0.002826
Name: Price_Change_24H, Length: 100, dtype: float64
Negative values:  60

In [16]:
# Price_Change_Percentage_24H column

print("missing values  ",df["Price_Change_Percentage_24H"].isnull().sum())
print("Duplicatedd    ",df["Price_Change_Percentage_24H"].duplicated().sum())
print("Value counts  ",df["Price_Change_Percentage_24H"].value_counts())

print("zero values=",(df["Price_Change_Percentage_24H"]==0).sum())
df["Price_Change_Percentage_24H"]=df["Price_Change_Percentage_24H"].replace(0,np.nan)
print(df["Price_Change_Percentage_24H"])
# fill missing values
df["Price_Change_Percentage_24H"]=df["Price_Change_Percentage_24H"].fillna(df["Price_Change_Percentage_24H"].median())
print(df["Price_Change_Percentage_24H"])

print("Negative values: ",(df["Price_Change_Percentage_24H"]< 0).sum())

missing values   1
Duplicatedd     5
Value counts   Price_Change_Percentage_24H
 0.00000    6
-0.96580    1
-0.26424    1
-0.03088    1
 1.76611    1
           ..
 9.87253    1
-0.47796    1
-1.06948    1
-2.74002    1
 0.36982    1
Name: count, Length: 94, dtype: int64
zero values= 6
0    -0.96580
1    -0.26424
2    -0.03088
3     1.76611
4    -0.15775
       ...
95    9.87253
96   -0.47796
97   -1.06948
98   -2.74002
99    0.36982
Name: Price_Change_Percentage_24H, Length: 100, dtype: float64
0    -0.96580
1    -0.26424
2    -0.03088
3     1.76611
4    -0.15775
       ...
95    9.87253
96   -0.47796
97   -1.06948
98   -2.74002
99    0.36982
Name: Price_Change_Percentage_24H, Length: 100, dtype: float64
Negative values:  59

In [17]:
# Market_Cap_Change_24H column

print("missing values  ",df["Market_Cap_Change_24H"].isnull().sum())
print("Duplicatedd    ",df["Market_Cap_Change_24H"].duplicated().sum())
print("Value counts  ",df["Market_Cap_Change_24H"].value_counts())

print("zero values=",(df["Market_Cap_Change_24H"]==0).sum())
df["Market_Cap_Change_24H"]=df["Market_Cap_Change_24H"].replace(0,np.nan)
print(df["Market_Cap_Change_24H"])
# fill missing values
df["Market_Cap_Change_24H"]=df["Market_Cap_Change_24H"].fillna(df["Market_Cap_Change_24H"].median())
print(df["Market_Cap_Change_24H"])

print("Negative values: ",(df["Market_Cap_Change_24H"]< 0).sum())

missing values   1
Duplicatedd     3
Value counts   Market_Cap_Change_24H
 0.000000e+00    4
-1.560238e+10    1
-8.336121e+08    1
-2.588648e+07    1
 1.727979e+09    1
                ..
 5.531087e+07    1
-3.146309e+06    1
-6.295168e+06    1
-1.588049e+07    1
 2.750147e+06    1
Name: count, Length: 96, dtype: int64
zero values= 4
0    -1.560238e+10
1    -8.336121e+08
2    -2.588648e+07
3     1.727979e+09
4    -1.240777e+08
          ...
95    5.531087e+07
96   -3.146309e+06
97   -6.295168e+06
98   -1.588049e+07
99    2.750147e+06
Name: Market_Cap_Change_24H, Length: 100, dtype: float64
0    -1.560238e+10
1    -8.336121e+08
2    -2.588648e+07
3     1.727979e+09
4    -1.240777e+08
          ...
95    5.531087e+07
96   -3.146309e+06
97   -6.295168e+06
98   -1.588049e+07
99    2.750147e+06
Name: Market_Cap_Change_24H, Length: 100, dtype: float64
Negative values:  54

In [18]:
# Market_Cap_Change_Percentage_24H column
print("missing values  ",df["Market_Cap_Change_Percentage_24H"].isnull().sum())
print("Duplicatedd    ",df["Market_Cap_Change_Percentage_24H"].duplicated().sum())
print("Value counts  ",df["Market_Cap_Change_Percentage_24H"].value_counts())

print("zero values=",(df["Market_Cap_Change_Percentage_24H"]==0).sum())
df["Market_Cap_Change_Percentage_24H"]=df["Market_Cap_Change_Percentage_24H"].replace(0,np.nan)
print(df["Market_Cap_Change_Percentage_24H"])
# fill missing values
df["Market_Cap_Change_Percentage_24H"]=df["Market_Cap_Change_Percentage_24H"].fillna(df["Market_Cap_Change_Percentage_24H"].median())
print(df["Market_Cap_Change_Percentage_24H"])

print("Negative values: ",(df["Market_Cap_Change_Percentage_24H"]< 0).sum())

missing values   1
Duplicatedd     4
Value counts   Market_Cap_Change_Percentage_24H
 0.00000    5
-0.97839    1
-0.27429    1
-0.01412    1
 1.74343    1
           ..
 9.71728    1
-0.50550    1
-1.01876    1
-2.67328    1
 0.48318    1
Name: count, Length: 95, dtype: int64
zero values= 5
0    -0.97839
1    -0.27429
2    -0.01412
3     1.74343
4    -0.14119
       ...
95    9.71728
96   -0.50550
97   -1.01876
98   -2.67328
99    0.48318
Name: Market_Cap_Change_Percentage_24H, Length: 100, dtype: float64
0    -0.97839
1    -0.27429
2    -0.01412
3     1.74343
4    -0.14119
       ...
95    9.71728
96   -0.50550
97   -1.01876
98   -2.67328
99    0.48318
Name: Market_Cap_Change_Percentage_24H, Length: 100, dtype: float64
Negative values:  55

In [20]:
# Circulating_Supply column


print("missing values  ",df["Circulating_Supply"].isnull().sum())
print("Duplicatedd    ",df["Circulating_Supply"].duplicated().sum())
print("Value counts  ",df["Circulating_Supply"].value_counts())

print("zero values=",(df["Circulating_Supply"]==0).sum())

print("Negative values: ",(df["Circulating_Supply"]< 0).sum())

print("Infinite value:", np.isinf(df['Circulating_Supply']).sum())

missing values   0
Duplicatedd     0
Value counts   Circulating_Supply
2.008136e+07    1
1.220297e+08    1
1.834386e+11    1
1.331615e+08    1
6.274450e+10    1
               ..
1.000000e+08    1
2.731371e+08    1
7.870569e+09    1
1.994669e+10    1
9.653500e+08    1
Name: count, Length: 100, dtype: int64
zero values= 0
Negative values:  0
Infinite value: 0

In [21]:
# Total_Supplycolumn


print("missing values  ",df["Total_Supply"].isnull().sum())
print("Duplicatedd    ",df["Total_Supply"].duplicated().sum())
print("Value counts  ",df["Total_Supply"].value_counts())

print("zero values=",(df["Total_Supply"]==0).sum())

print("Negative values: ",(df["Total_Supply"]< 0).sum())

print("Infinite value:", np.isinf(df['Total_Supply']).sum())

# check unique value
print("unique:",df['Total_Supply'].unique())

missing values   0
Duplicatedd     10
Value counts   Total_Supply
1.000000e+09    5
1.000000e+10    5
2.100000e+07    2
1.000000e+11    2
2.008138e+07    1
               ..
1.973685e+09    1
1.000000e+08    1
9.939509e+09    1
3.806569e+10    1
9.653500e+08    1
Name: count, Length: 90, dtype: int64
zero values= 0
Negative values:  0
Infinite value: 0
unique: [2.00813840e+07 1.22029705e+08 1.88905526e+11 1.33161511e+08
 9.99856277e+10 7.43090524e+10 6.33642586e+08 9.49408293e+10
 2.22920127e+10 1.69210939e+07 9.55307079e+08 1.71540993e+11
 1.14240853e+12 9.84652286e+09 1.88019154e+07 1.00000000e+09
 2.93606018e+08 9.85239504e+08 4.50000000e+10 5.00017868e+10
 2.00865999e+07 4.60424409e+09 4.39864357e+09 8.90460420e+08
 7.75874731e+07 4.26004989e+09 3.95512379e+10 5.24544555e+09
 5.00000000e+10 4.63441061e+08 1.00000000e+10 3.24882346e+09
 5.89496239e+14 1.30575137e+09 2.88953954e+09 9.89082992e+10
 2.83228287e+09 7.07747089e+05 5.41181335e+09 2.30898805e+09
 2.10000000e+07 2.43365138e+09 1.92611331e+09 6.21931679e+09
 7.80396812e+09 1.60000000e+07 4.32503322e+05 1.70179729e+09
 1.00000000e+11 8.35145299e+11 5.56249925e+08 1.50000000e+10
 2.34626651e+10 4.20690000e+14 8.98232729e+14 1.46333710e+09
 9.10920875e+08 1.36545441e+09 1.34409743e+09 1.32000000e+09
 1.58100715e+08 1.29299931e+09 1.05869729e+09 1.71410471e+10
 1.07106169e+10 1.18872055e+08 1.46124930e+07 9.11211100e+06
 2.76883902e+10 1.42155021e+08 7.18062999e+08 5.29545464e+08
 9.03953427e+09 8.09654778e+07 8.18874304e+09 6.86243120e+09
 1.28297598e+07 7.17141158e+08 5.33532275e+08 6.91601979e+07
 3.31857365e+08 6.78300455e+08 1.95708384e+09 6.99000000e+08
 8.59850412e+10 1.97368509e+09 1.00000000e+08 9.93950941e+09
 3.80656864e+10 9.65350000e+08]

In [22]:
# max supply column

print("missing values  ",df["Max_Supply"].isnull().sum())
print("Duplicatedd    ",df["Max_Supply"].duplicated().sum())
print("Value counts  ",df["Max_Supply"].value_counts())

print("zero values=",(df["Max_Supply"]==0).sum())

# fill missing values
df["Max_Supply"]=df["Max_Supply"].fillna(df["Max_Supply"].median())
print(df["Max_Supply"])

print("Negative values: ",(df["Max_Supply"]< 0).sum())

missing values   48
Duplicatedd     70
Value counts   Max_Supply
1.000000e+09    8
1.000000e+10    8
2.100000e+07    5
1.000000e+11    5
4.000000e+08    2
2.000000e+08    1
1.150000e+12    1
4.500000e+10    1
8.400000e+07    1
5.000000e+10    1
7.200000e+08    1
6.219317e+09    1
8.000000e+09    1
1.600000e+07    1
2.100000e+09    1
1.000000e+12    1
1.500000e+10    1
2.346267e+10    1
4.206900e+14    1
9.999900e+14    1
2.000000e+09    1
2.107000e+08    1
1.426228e+08    1
1.461249e+07    1
2.870403e+10    1
9.900000e+09    1
1.892000e+07    1
6.442451e+08    1
8.671263e+10    1
Name: count, dtype: int64
zero values= 0
0     2.100000e+07
1     4.159658e+09
2     4.159658e+09
3     2.000000e+08
4     1.000000e+11
          ...
95    4.159658e+09
96    1.000000e+09
97    4.159658e+09
98    4.159658e+09
99    1.000000e+09
Name: Max_Supply, Length: 100, dtype: float64
Negative values:  0

In [23]:
# Ath column

print("missing values  ",df["Ath"].isnull().sum())
print("Duplicatedd    ",df["Ath"].duplicated().sum())
print("Value counts  ",df["Ath"].value_counts())

print("zero values=",(df["Ath"]==0).sum())
print("Negative values: ",(df["Ath"]< 0).sum())

missing values   0
Duplicatedd     2
Value counts   Ath
1.048000         2
1.260000         2
126080.000000    1
4946.050000      1
1.320000         1
                ..
52.620000        1
73.430000        1
0.450785         1
0.192754         1
8.530000         1
Name: count, Length: 98, dtype: int64
zero values= 0
Negative values:  0

In [24]:
# Ath_Change_Percentage column

print("missing values  ",df["Ath_Change_Percentage"].isnull().sum())
print("Duplicatedd    ",df["Ath_Change_Percentage"].duplicated().sum())
print("Value counts  ",df["Ath_Change_Percentage"].value_counts())

print("zero values=",(df["Ath_Change_Percentage"]==0).sum())
print("Negative values: ",(df["Ath_Change_Percentage"]< 0).sum())

missing values   0
Duplicatedd     4
Value counts   Ath_Change_Percentage
 0.00000     5
-37.63171    1
-49.78373    1
-24.44896    1
-44.72041    1
            ..
-88.13089    1
-96.91194    1
-82.76120    1
-84.96358    1
-93.05383    1
Name: count, Length: 96, dtype: int64
zero values= 5
Negative values:  95

In [25]:
# Ath_Date column

print("missing values  ",df["Ath_Date"].isnull().sum())
print("Duplicatedd    ",df["Ath_Date"].duplicated().sum())
print("Value counts  ",df["Ath_Date"].value_counts())

df["Ath_Date"]=pd.to_datetime(df["Ath_Date"],errors="coerce")

print("unique:",df['Ath_Date'])

df["Ath_Date"]=df["Ath_Date"].astype(str).str.strip()

missing values   0
Duplicatedd     2
Value counts   Ath_Date
2017-12-19T16:00:00.000Z    2
2026-09-04T07:25:10.000Z    2
2025-10-06T10:57:42.000Z    1
2025-08-24T11:21:03.000Z    1
2018-07-23T16:00:00.000Z    1
                           ..
2024-03-14T07:06:22.000Z    1
2025-01-19T03:50:34.000Z    1
2018-12-16T16:00:00.000Z    1
2021-08-20T20:39:48.000Z    1
2024-03-27T15:14:46.000Z    1
Name: count, Length: 98, dtype: int64
unique: 0    2025-10-06 10:57:42+00:00
1    2025-08-24 11:21:03+00:00
2    2018-07-23 16:00:00+00:00
3    2025-10-13 00:41:24+00:00
4    2025-07-17 19:40:53+00:00
                ...
95   2024-03-14 07:06:22+00:00
96   2025-01-19 03:50:34+00:00
97   2018-12-16 16:00:00+00:00
98   2021-08-20 20:39:48+00:00
99   2024-03-27 15:14:46+00:00
Name: Ath_Date, Length: 100, dtype: datetime64[us, UTC]

In [26]:
# Atlcolumn


print("missing values  ",df["Atl"].isnull().sum())
print("Duplicatedd    ",df["Atl"].duplicated().sum())
print("Value counts  ",df["Atl"].value_counts())

print("zero values=",(df["Atl"]==0).sum())
print("Negative values: ",(df["Atl"]< 0).sum())

missing values   0
Duplicatedd     1
Value counts   Atl
1.150000     2
67.810000    1
0.432979     1
0.572521     1
0.039818     1
            ..
0.657401     1
1.370000     1
0.000275     1
0.000395     1
0.266530     1
Name: count, Length: 99, dtype: int64
zero values= 0
Negative values:  0

In [27]:
# Atl_Change_Percentage column

print("missing values  ",df["Atl_Change_Percentage"].isnull().sum())
print("Duplicatedd    ",df["Atl_Change_Percentage"].duplicated().sum())
print("Value counts  ",df["Atl_Change_Percentage"].value_counts())

print("zero values=",(df["Atl_Change_Percentage"]==0).sum())
print("Negative values: ",(df["Atl_Change_Percentage"]< 0).sum())

missing values   0
Duplicatedd     0
Value counts   Atl_Change_Percentage
1.158638e+05    1
5.735357e+05    1
7.459836e+01    1
1.901883e+06    1
5.196478e+04    1
               ..
8.500454e+02    1
6.548837e+01    1
2.813909e+04    1
7.231643e+03    1
1.222760e+02    1
Name: count, Length: 100, dtype: int64
zero values= 1
Negative values:  0

In [28]:
#Atl_Datecolumn

print("missing values  ",df["Atl_Date"].isnull().sum())
print("Duplicatedd    ",df["Atl_Date"].duplicated().sum())
print("Value counts  ",df["Atl_Date"].value_counts())

df["Atl_Date"]=pd.to_datetime(df["Atl_Date"],errors="coerce")

print("unique:",df['Atl_Date'])

df["Atl_Date"]=df["Atl_Date"].astype(str).str.strip()

missing values   0
Duplicatedd     1
Value counts   Atl_Date
2015-01-13T16:00:00.000Z    2
2013-07-05T16:00:00.000Z    1
2015-10-19T16:00:00.000Z    1
2015-03-01T16:00:00.000Z    1
2017-10-18T16:00:00.000Z    1
                           ..
2020-11-03T08:19:30.000Z    1
2026-08-13T18:40:30.000Z    1
2019-11-01T03:05:12.000Z    1
2019-07-21T16:00:00.000Z    1
2026-06-05T19:19:15.000Z    1
Name: count, Length: 99, dtype: int64
unique: 0    2013-07-05 16:00:00+00:00
1    2015-10-19 16:00:00+00:00
2    2015-03-01 16:00:00+00:00
3    2017-10-18 16:00:00+00:00
4    2014-05-21 16:00:00+00:00
                ...
95   2020-11-03 08:19:30+00:00
96   2026-08-13 18:40:30+00:00
97   2019-11-01 03:05:12+00:00
98   2019-07-21 16:00:00+00:00
99   2026-06-05 19:19:15+00:00
Name: Atl_Date, Length: 100, dtype: datetime64[us, UTC]

In [29]:
# Roi column
df.drop('Roi', axis=1, inplace=True)

In [30]:
# Last_Updated column

print("missing values  ",df["Ath_Change_Percentage"].isnull().sum())
print("Duplicatedd    ",df["Ath_Change_Percentage"].duplicated().sum())
print("Value counts  ",df["Ath_Change_Percentage"].value_counts())


print("zero value:", (df['Last_Updated'] == 0).sum())
print("-"*50)

print("unique values:", df['Last_Updated'].nunique())

missing values   0
Duplicatedd     4
Value counts   Ath_Change_Percentage
 0.00000     5
-37.63171    1
-49.78373    1
-24.44896    1
-44.72041    1
            ..
-88.13089    1
-96.91194    1
-82.76120    1
-84.96358    1
-93.05383    1
Name: count, Length: 96, dtype: int64
zero value: 0
--------------------------------------------------
unique values: 2

In [31]:
df.columns

Index(['Unnamed: 0', 'Id', 'Symbol', 'Name', 'Image', 'Current_Price',
       'Market_Cap', 'Market_Cap_Rank', 'Fully_Diluted_Valuation',
       'Total_Volume', 'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Last_Updated'],
      dtype='str')

In [32]:
df

,Unnamed: 0,Id,Symbol,Name,Image,Current_Price,Market_Cap,Market_Cap_Rank,Fully_Diluted_Valuation,Total_Volume,...,Circulating_Supply,Total_Supply,Max_Supply,Ath,Ath_Change_Percentage,Ath_Date,Atl,Atl_Change_Percentage,Atl_Date,Last_Updated
0,0,Bitcoin,Btc,Bitcoin,[https://coin-images.coingecko.com/coins/image...,78634.000000,1579089652770,1,1579090360482,2.838799e+10,...,2.008136e+07,2.008138e+07,2.100000e+07,126080.000000,-37.63171,2025-10-06 10:57:42+00:00,67.810000,1.158638e+05,2013-07-05 16:00:00+00:00,2026-09-08T10:46:30.000Z
1,1,Ethereum,Eth,Ethereum,[https://coin-images.coingecko.com/coins/image...,2483.720000,303085220706,2,303085220706,1.078036e+10,...,1.220297e+08,1.220297e+08,4.159658e+09,4946.050000,-49.78373,2025-08-24 11:21:03+00:00,0.432979,5.735357e+05,2015-10-19 16:00:00+00:00,2026-09-08T10:46:30.000Z
2,2,Tether,Usdt,Tether,[https://coin-images.coingecko.com/coins/image...,0.999612,183369701757,3,188834594823,5.236984e+10,...,1.834386e+11,1.889055e+11,4.159658e+09,1.320000,-24.44896,2018-07-23 16:00:00+00:00,0.572521,7.459836e+01,2015-03-01 16:00:00+00:00,2026-09-08T10:46:30.000Z
3,3,Binancecoin,Bnb,Bnb,[https://coin-images.coingecko.com/coins/image...,757.330000,100841624829,4,100841628010,1.107447e+09,...,1.331615e+08,1.331615e+08,2.000000e+08,1369.990000,-44.72041,2025-10-13 00:41:24+00:00,0.039818,1.901883e+06,2017-10-18 16:00:00+00:00,2026-09-08T10:46:30.000Z
4,4,Ripple,Xrp,Xrp,[https://coin-images.coingecko.com/coins/image...,1.400000,87754936306,5,139840650751,1.896142e+09,...,6.274450e+10,9.998563e+10,1.000000e+11,3.650000,-61.64502,2025-07-17 19:40:53+00:00,0.002686,5.196478e+04,2014-05-21 16:00:00+00:00,2026-09-08T10:46:30.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,Injective-Protocol,Inj,Injective,[https://coin-images.coingecko.com/coins/image...,6.250000,624512089,95,624512089,2.333809e+08,...,1.000000e+08,1.000000e+08,4.159658e+09,52.620000,-88.13089,2024-03-14 07:06:22+00:00,0.657401,8.500454e+02,2020-11-03 08:19:30+00:00,2026-09-08T10:46:30.000Z
96,96,Official-Trump,Trump,Official Trump,[https://coin-images.coingecko.com/coins/image...,2.270000,619265191,96,2267231895,1.876301e+08,...,2.731371e+08,1.000000e+09,1.000000e+09,73.430000,-96.91194,2025-01-19 03:50:34+00:00,1.370000,6.548837e+01,2026-08-13 18:40:30+00:00,2026-09-08T10:46:30.000Z
97,97,Beldex,Bdx,Beldex,[https://coin-images.coingecko.com/coins/image...,0.077710,611626584,97,772405069,1.099994e+07,...,7.870569e+09,9.939509e+09,4.159658e+09,0.450785,-82.76120,2018-12-16 16:00:00+00:00,0.000275,2.813909e+04,2019-11-01 03:05:12+00:00,2026-09-08T10:46:30.000Z
98,98,Xdce-Crowd-Sale,Xdc,Xdc Network,[https://coin-images.coingecko.com/coins/image...,0.028983,578165056,98,1103353562,7.305587e+06,...,1.994669e+10,3.806569e+10,4.159658e+09,0.192754,-84.96358,2021-08-20 20:39:48+00:00,0.000395,7.231643e+03,2019-07-21 16:00:00+00:00,2026-09-08T10:46:30.000Z
99,99,Ether-Fi,Ethfi,Ether.Fi,[https://coin-images.coingecko.com/coins/image...,0.592432,571926334,99,571926334,5.618779e+07,...,9.653500e+08,9.653500e+08,1.000000e+09,8.530000,-93.05383,2024-03-27 15:14:46+00:00,0.266530,1.222760e+02,2026-06-05 19:19:15+00:00,2026-09-08T10:46:30.000Z

In [33]:
df.to_csv("cleaned_coin_dataset.csv")