In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\Advanced_Multi-Source_Data_Pipeline\\CoinGeko_Analysis\\Scraped_crypto(1).csv")
df

,Unnamed: 0,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,76869.000000,1543780270779,1,1543789572409,3.415245e+10,...,2.008236e+07,2.100000e+07,126080.000000,-39.03115,2025-10-06T10:57:42.000Z,67.810000,1.132617e+05,2013-07-05T16:00:00.000Z,NaN,2026-09-10T13:27:20.000Z
1,1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2417.760000,295019194043,2,295019194043,1.358600e+10,...,1.220356e+08,NaN,4946.050000,-51.11726,2025-08-24T11:21:03.000Z,0.432979,5.583024e+05,2015-10-19T16:00:00.000Z,"{'times': 41.039136156189585, 'currency': 'btc...",2026-09-10T13:27:20.000Z
2,2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999689,183399747382,3,188864872668,5.765036e+10,...,1.889278e+11,NaN,1.320000,-24.44314,2018-07-23T16:00:00.000Z,0.572521,7.461181e+01,2015-03-01T16:00:00.000Z,NaN,2026-09-10T13:27:20.000Z
3,3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,706.520000,94081938222,4,94081937558,1.262140e+09,...,1.331612e+08,2.000000e+08,1369.990000,-48.42904,2025-10-13T00:41:24.000Z,0.039818,1.774281e+06,2017-10-18T16:00:00.000Z,NaN,2026-09-10T13:27:20.000Z
4,4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.360000,85090865143,5,135595357428,2.406497e+09,...,9.998563e+10,1.000000e+11,3.650000,-62.80759,2025-07-17T19:40:53.000Z,0.002686,5.038666e+04,2014-05-21T16:00:00.000Z,NaN,2026-09-10T13:27:20.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,beldex,bdx,Beldex,https://coin-images.coingecko.com/coins/images...,0.076862,604714731,96,763675850,1.169582e+07,...,9.939535e+09,NaN,0.450785,-82.94928,2018-12-16T16:00:00.000Z,0.000275,2.783099e+04,2019-11-01T03:05:12.000Z,"{'times': -0.6928350698556385, 'currency': 'us...",2026-09-10T13:27:20.000Z
96,96,injective-protocol,inj,Injective,https://coin-images.coingecko.com/coins/images...,5.930000,593229023,97,593229023,8.349674e+07,...,1.000000e+08,NaN,52.620000,-88.72517,2024-03-14T07:06:22.000Z,0.657401,8.024772e+02,2020-11-03T08:19:30.000Z,NaN,2026-09-10T13:27:20.000Z
97,97,xdce-crowd-sale,xdc,XDC Network,https://coin-images.coingecko.com/coins/images...,0.028112,560726767,98,1070074832,5.787636e+06,...,3.806569e+10,NaN,0.192754,-85.41580,2021-08-20T20:39:48.000Z,0.000395,7.011147e+03,2019-07-21T16:00:00.000Z,"{'times': 0.5449029760011064, 'currency': 'eth...",2026-09-10T13:27:20.000Z
98,98,flare-networks,flr,Flare,https://coin-images.coingecko.com/coins/images...,0.006346,551497765,99,675979791,3.149003e+06,...,1.065179e+11,NaN,0.150073,-95.77151,2023-01-09T19:14:05.000Z,0.005860,8.282510e+00,2026-08-19T10:09:30.000Z,NaN,2026-09-10T13:27:20.000Z
99,99,usual-usd,usd0,Usual USD,https://coin-images.coingecko.com/coins/images...,0.997173,546890845,100,546890845,2.004420e+05,...,5.484531e+08,NaN,1.330000,-24.78136,2024-07-12T00:28:59.000Z,0.962885,3.561000e+00,2025-04-10T00:30:51.000Z,NaN,2026-09-10T13:27:20.000Z

In [4]:
# standardising the column name

df.columns=df.columns.str.strip().str.title()

In [5]:
# ID column

# column values into title case
df["Id"]=df["Id"].str.strip().str.title()
df["Id"].isnull().sum()
df["Id"].duplicated().sum()
df["Id"].unique()

<StringArray>
[                                                     'Bitcoin',
                                                     'Ethereum',
                                                       'Tether',
                                                  'Binancecoin',
                                                       'Ripple',
                                                     'Usd-Coin',
                                                       'Solana',
                                                         'Tron',
                                                 'Figure-Heloc',
                                                        'Zcash',
                                                  'Hyperliquid',
                                                     'Dogecoin',
                                                         'Rain',
                                                         'Usds',
                                                       'Monero',
                                                     'Whitebit',
                                                    'Chainlink',
                                                    'Leo-Token',
                                                      'Cardano',
                                                      'Stellar',
                                                 'Bitcoin-Cash',
                                                          'Dai',
                                                  'Ethena-Usde',
                                                    'Usd1-Wlfi',
                                                     'Litecoin',
                                               'Canton-Network',
                                             'The-Open-Network',
                                                      'Uniswap',
                                                'Global-Dollar',
                                             'Hedera-Hashgraph',
                                                  'Avalanche-2',
                                                         'Near',
                                                          'Sui',
                                                    'Shiba-Inu',
                                                   'Paypal-Usd',
           'Blackrock-Usd-Institutional-Digital-Liquidity-Fund',
                                             'Crypto-Com-Chain',
                                                     'Memecore',
                                                  'Tether-Gold',
                                                'Hashnote-Usyc',
                                                   'Ripple-Usd',
                                                    'Bittensor',
                                                          'Okb',
                                         'Ondo-Us-Dollar-Yield',
                                                       'Mantle',
                                                      'Aster-2',
                                                     'Pax-Gold',
                                                         'Aave',
                                                     'Polkadot',
                                      'World-Liberty-Financial',
                                                 'Ondo-Finance',
                                                     'Pump-Fun',
                                                       'Morpho',
                                            'Internet-Computer',
                                                      'Htx-Dao',
                                                'Worldcoin-Wld',
                                                         'Usdd',
                                                       'Ethena',
                                                         'Pepe',
                                                        'Usdgo',
                                                          'Sky',
                                                 'Bitget-Token',
                                               'Falcon-Finance',
                                                        'Bfusd',
                         'Spiko-Amundi-Overnight-Swap-Fund-Eur',
                                               'United-Stables',
                                                       'Bitway',
                                             'Ethereum-Classic',
                                                 'Venice-Token',
                                                      'Lighter',
                                                   'Pi-Network',
                                                        'Kaspa',
                                                     'Arbitrum',
                                      'Polygon-Ecosystem-Token',
                                           'Blockchain-Capital',
                                              'Gatechain-Token',
                                                       'Cosmos',
                                                'Quant-Network',
                                                'Kucoin-Shares',
                                                     'Algorand',
                                                        'Eutbl',
                                                         'Just',
                                                         'Nexo',
 'Superstate-Short-Duration-Us-Government-Securities-Fund-Ustb',
                                                     'Stable-2',
                         'Janus-Henderson-Anemoy-Treasury-Fund',
                                      'Jupiter-Exchange-Solana',
                                                 'Render-Token',
                                                         'Dash',
                          'Janus-Henderson-Anemoy-Aaa-Clo-Fund',
                                                          'Gho',
                                                      'Vechain',
                                            'Pancakeswap-Token',
                                                     'Filecoin',
                                                     'Ether-Fi',
                                                       'Beldex',
                                           'Injective-Protocol',
                                              'Xdce-Crowd-Sale',
                                               'Flare-Networks',
                                                    'Usual-Usd']
Length: 100, dtype: str

In [6]:
# symbol column

df["Symbol"]=df["Symbol"].str.strip().str.title().astype("string")
df["Symbol"].isnull().sum()
df["Symbol"].duplicated().sum()

np.int64(0)

In [7]:
# name column
df["Name"]=df["Name"].str.strip().str.title()
df["Name"].isnull().sum()
df["Name"].duplicated().sum()

np.int64(0)

In [8]:
# Image column
df["Image"]=df["Image"].str.split()
df["Image"].isnull().sum()
df["Image"].duplicated().sum()

np.int64(0)

In [9]:
# current price column
df["Current_Price"].isnull().sum()
df["Current_Price"].duplicated().sum()
df["Current_Price"].value_counts()

print("zero values=",(df["Current_Price"]==0).sum())

print("Negative values: ",(df["Current_Price"]< 0).sum())

zero values= 0
Negative values:  0

In [10]:
# market cap columnn\

df["Market_Cap"].isnull().sum()
df["Market_Cap"].duplicated().sum()
df["Market_Cap"].value_counts()
df["Market_Cap"].dtype

print("Zero value: ",(df["Market_Cap"]==0).sum())
print("negative value: ",(df["Market_Cap"]<0).sum())

Zero value:  0
negative value:  0

In [11]:
# Market_Cap_Rank column
print(df["Market_Cap_Rank"].isna().sum())

df["Market_Cap_Rank"].duplicated().sum()

print("Zero value: ",(df["Market_Cap_Rank"]==0).sum())

print("-ve value: ",(df["Market_Cap_Rank"]<0).sum())

0
Zero value:  0
-ve value:  0

In [12]:
# Fully_Diluted_Valuation column

df["Fully_Diluted_Valuation"].isnull().sum()

df["Fully_Diluted_Valuation"].duplicated().sum()

print("Zero Value: ",(df["Fully_Diluted_Valuation"]==0).sum())
# convert 0 into the nan values
df["Fully_Diluted_Valuation"]=df["Fully_Diluted_Valuation"].replace(0,np.nan)
df["Fully_Diluted_Valuation"]

print("negative Value: ",(df["Fully_Diluted_Valuation"]<0).sum())

# check the missing values
print("Missing values: ",df["Fully_Diluted_Valuation"].isna().sum())

Zero Value:  0
negative Value:  0
Missing values:  0

In [13]:
# Total_Volume column
df["Total_Volume"].isnull().sum()

df["Total_Volume"].duplicated().sum()

print("Zero Value: ",(df["Total_Volume"]==0).sum())
# check their percentage
print("zero_per:",(df['Total_Volume'] == 0).mean()*100)
print("-"*50)

# replace 0 eith nan
df["Total_Volume"]=df["Total_Volume"].replace(0,np.nan)
print(df["Total_Volume"])

df["Total_Volume"].dtype

Zero Value:  8
zero_per: 8.0
--------------------------------------------------
0     3.415245e+10
1     1.358600e+10
2     5.765036e+10
3     1.262140e+09
4     2.406497e+09
          ...
95    1.169582e+07
96    8.349674e+07
97    5.787636e+06
98    3.149003e+06
99    2.004420e+05
Name: Total_Volume, Length: 100, dtype: float64

dtype('float64')

In [14]:
# High_24H column
print("missing values  ",df["High_24H"].isnull().sum())
print("Duplicatedd    ",df["High_24H"].duplicated().sum())
print("Value counts  ",df["High_24H"].value_counts())

print("zero values=",(df["High_24H"]==0).sum())
df["High_24H"]=df["High_24H"].replace(0,np.nan)
print(df["High_24H"])
# fill missing values
df["High_24H"]=df["High_24H"].fillna(df["High_24H"].median())
print(df["High_24H"])

print("Negative values: ",(df["High_24H"]< 0).sum())

missing values   0
Duplicatedd     8
Value counts   High_24H
1.000000        8
1.230000        2
79351.000000    1
2513.050000     1
0.999919        1
               ..
0.077063        1
6.250000        1
0.028855        1
0.006470        1
0.999036        1
Name: count, Length: 92, dtype: int64
zero values= 0
0     79351.000000
1      2513.050000
2         0.999919
3       746.280000
4         1.430000
          ...
95        0.077063
96        6.250000
97        0.028855
98        0.006470
99        0.999036
Name: High_24H, Length: 100, dtype: float64
0     79351.000000
1      2513.050000
2         0.999919
3       746.280000
4         1.430000
          ...
95        0.077063
96        6.250000
97        0.028855
98        0.006470
99        0.999036
Name: High_24H, Length: 100, dtype: float64
Negative values:  0

In [15]:
# Low_24H column

print("missing values  ",df["Low_24H"].isnull().sum())
print("Duplicatedd    ",df["Low_24H"].duplicated().sum())
print("Value counts  ",df["Low_24H"].value_counts())

print("zero values=",(df["Low_24H"]==0).sum())
df["Low_24H"]=df["Low_24H"].replace(0,np.nan)
print(df["Low_24H"])
# fill missing values
df["Low_24H"]=df["Low_24H"].fillna(df["Low_24H"].median())
print(df["Low_24H"])

print("Negative values: ",(df["Low_24H"]< 0).sum())

missing values   0
Duplicatedd     2
Value counts   Low_24H
1.350000        2
1.140000        2
76748.000000    1
2413.620000     1
0.999558        1
               ..
0.076083        1
5.900000        1
0.028061        1
0.006341        1
0.998624        1
Name: count, Length: 98, dtype: int64
zero values= 0
0     76748.000000
1      2413.620000
2         0.999558
3       704.860000
4         1.350000
          ...
95        0.076083
96        5.900000
97        0.028061
98        0.006341
99        0.998624
Name: Low_24H, Length: 100, dtype: float64
0     76748.000000
1      2413.620000
2         0.999558
3       704.860000
4         1.350000
          ...
95        0.076083
96        5.900000
97        0.028061
98        0.006341
99        0.998624
Name: Low_24H, Length: 100, dtype: float64
Negative values:  0

In [16]:
# Price_Change_24H column

print("missing values  ",df["Price_Change_24H"].isnull().sum())
print("Duplicatedd    ",df["Price_Change_24H"].duplicated().sum())
print("Value counts  ",df["Price_Change_24H"].value_counts())

print("zero values=",(df["Price_Change_24H"]==0).sum())
df["Price_Change_24H"]=df["Price_Change_24H"].replace(0,np.nan)
print(df["Price_Change_24H"])
# fill missing values
df["Price_Change_24H"]=df["Price_Change_24H"].fillna(df["Price_Change_24H"].median())
print(df["Price_Change_24H"])

print("Negative values: ",(df["Price_Change_24H"]< 0).sum())

missing values   0
Duplicatedd     2
Value counts   Price_Change_24H
 0.000000       3
-2710.455694    1
-96.662487      1
-0.000115       1
-43.968827      1
               ..
 0.000371       1
-0.329133       1
-0.000759       1
-0.000121       1
-0.001529       1
Name: count, Length: 98, dtype: int64
zero values= 3
0    -2710.455694
1      -96.662487
2       -0.000115
3      -43.968827
4       -0.079153
         ...
95       0.000371
96      -0.329133
97      -0.000759
98      -0.000121
99      -0.001529
Name: Price_Change_24H, Length: 100, dtype: float64
0    -2710.455694
1      -96.662487
2       -0.000115
3      -43.968827
4       -0.079153
         ...
95       0.000371
96      -0.329133
97      -0.000759
98      -0.000121
99      -0.001529
Name: Price_Change_24H, Length: 100, dtype: float64
Negative values:  83

In [17]:
# Price_Change_Percentage_24H column

print("missing values  ",df["Price_Change_Percentage_24H"].isnull().sum())
print("Duplicatedd    ",df["Price_Change_Percentage_24H"].duplicated().sum())
print("Value counts  ",df["Price_Change_Percentage_24H"].value_counts())

print("zero values=",(df["Price_Change_Percentage_24H"]==0).sum())
df["Price_Change_Percentage_24H"]=df["Price_Change_Percentage_24H"].replace(0,np.nan)
print(df["Price_Change_Percentage_24H"])
# fill missing values
df["Price_Change_Percentage_24H"]=df["Price_Change_Percentage_24H"].fillna(df["Price_Change_Percentage_24H"].median())
print(df["Price_Change_Percentage_24H"])

print("Negative values: ",(df["Price_Change_Percentage_24H"]< 0).sum())

missing values   0
Duplicatedd     2
Value counts   Price_Change_Percentage_24H
 0.00000    3
-3.39912    1
-3.82867    1
-0.00998    1
-5.86875    1
           ..
 0.45540    1
-5.38911    1
-2.61781    1
-1.87229    1
-0.15147    1
Name: count, Length: 98, dtype: int64
zero values= 3
0    -3.39912
1    -3.82867
2    -0.00998
3    -5.86875
4    -5.51561
       ...
95    0.45540
96   -5.38911
97   -2.61781
98   -1.87229
99   -0.15147
Name: Price_Change_Percentage_24H, Length: 100, dtype: float64
0    -3.39912
1    -3.82867
2    -0.00998
3    -5.86875
4    -5.51561
       ...
95    0.45540
96   -5.38911
97   -2.61781
98   -1.87229
99   -0.15147
Name: Price_Change_Percentage_24H, Length: 100, dtype: float64
Negative values:  82

In [18]:
# Market_Cap_Change_24H column

print("missing values  ",df["Market_Cap_Change_24H"].isnull().sum())
print("Duplicatedd    ",df["Market_Cap_Change_24H"].duplicated().sum())
print("Value counts  ",df["Market_Cap_Change_24H"].value_counts())

print("zero values=",(df["Market_Cap_Change_24H"]==0).sum())
df["Market_Cap_Change_24H"]=df["Market_Cap_Change_24H"].replace(0,np.nan)
print(df["Market_Cap_Change_24H"])
# fill missing values
df["Market_Cap_Change_24H"]=df["Market_Cap_Change_24H"].fillna(df["Market_Cap_Change_24H"].median())
print(df["Market_Cap_Change_24H"])

print("Negative values: ",(df["Market_Cap_Change_24H"]< 0).sum())

missing values   0
Duplicatedd     0
Value counts   Market_Cap_Change_24H
-5.433093e+10    1
-1.182273e+10    1
-2.455614e+07    1
-5.853884e+09    1
-4.968140e+09    1
                ..
 2.687703e+06    1
-3.297358e+07    1
-1.514827e+07    1
-1.048217e+07    1
-8.505120e+05    1
Name: count, Length: 100, dtype: int64
zero values= 1
0    -5.433093e+10
1    -1.182273e+10
2    -2.455614e+07
3    -5.853884e+09
4    -4.968140e+09
          ...
95    2.687703e+06
96   -3.297358e+07
97   -1.514827e+07
98   -1.048217e+07
99   -8.505120e+05
Name: Market_Cap_Change_24H, Length: 100, dtype: float64
0    -5.433093e+10
1    -1.182273e+10
2    -2.455614e+07
3    -5.853884e+09
4    -4.968140e+09
          ...
95    2.687703e+06
96   -3.297358e+07
97   -1.514827e+07
98   -1.048217e+07
99   -8.505120e+05
Name: Market_Cap_Change_24H, Length: 100, dtype: float64
Negative values:  82

In [19]:
# Market_Cap_Change_Percentage_24H column
print("missing values  ",df["Market_Cap_Change_Percentage_24H"].isnull().sum())
print("Duplicatedd    ",df["Market_Cap_Change_Percentage_24H"].duplicated().sum())
print("Value counts  ",df["Market_Cap_Change_Percentage_24H"].value_counts())

print("zero values=",(df["Market_Cap_Change_Percentage_24H"]==0).sum())
df["Market_Cap_Change_Percentage_24H"]=df["Market_Cap_Change_Percentage_24H"].replace(0,np.nan)
print(df["Market_Cap_Change_Percentage_24H"])
# fill missing values
df["Market_Cap_Change_Percentage_24H"]=df["Market_Cap_Change_Percentage_24H"].fillna(df["Market_Cap_Change_Percentage_24H"].median())
print(df["Market_Cap_Change_Percentage_24H"])

print("Negative values: ",(df["Market_Cap_Change_Percentage_24H"]< 0).sum())

missing values   0
Duplicatedd     0
Value counts   Market_Cap_Change_Percentage_24H
-3.39970    1
-3.85304    1
-0.01339    1
-5.85764    1
-5.51654    1
           ..
 0.44644    1
-5.26564    1
-2.63048    1
-1.86522    1
-0.15528    1
Name: count, Length: 100, dtype: int64
zero values= 1
0    -3.39970
1    -3.85304
2    -0.01339
3    -5.85764
4    -5.51654
       ...
95    0.44644
96   -5.26564
97   -2.63048
98   -1.86522
99   -0.15528
Name: Market_Cap_Change_Percentage_24H, Length: 100, dtype: float64
0    -3.39970
1    -3.85304
2    -0.01339
3    -5.85764
4    -5.51654
       ...
95    0.44644
96   -5.26564
97   -2.63048
98   -1.86522
99   -0.15528
Name: Market_Cap_Change_Percentage_24H, Length: 100, dtype: float64
Negative values:  82

In [20]:
# Circulating_Supply column


print("missing values  ",df["Circulating_Supply"].isnull().sum())
print("Duplicatedd    ",df["Circulating_Supply"].duplicated().sum())
print("Value counts  ",df["Circulating_Supply"].value_counts())

print("zero values=",(df["Circulating_Supply"]==0).sum())

print("Negative values: ",(df["Circulating_Supply"]< 0).sum())

print("Infinite value:", np.isinf(df['Circulating_Supply']).sum())

missing values   0
Duplicatedd     0
Value counts   Circulating_Supply
2.008222e+07    1
1.220356e+08    1
1.834608e+11    1
1.331612e+08    1
6.274450e+10    1
               ..
7.870595e+09    1
1.000000e+08    1
1.994669e+10    1
8.690260e+10    1
5.484531e+08    1
Name: count, Length: 100, dtype: int64
zero values= 0
Negative values:  0
Infinite value: 0

In [21]:
# Total_Supplycolumn


print("missing values  ",df["Total_Supply"].isnull().sum())
print("Duplicatedd    ",df["Total_Supply"].duplicated().sum())
print("Value counts  ",df["Total_Supply"].value_counts())

print("zero values=",(df["Total_Supply"]==0).sum())

print("Negative values: ",(df["Total_Supply"]< 0).sum())

print("Infinite value:", np.isinf(df['Total_Supply']).sum())

# check unique value
print("unique:",df['Total_Supply'].unique())

missing values   0
Duplicatedd     9
Value counts   Total_Supply
1.000000e+10    5
1.000000e+09    4
2.100000e+07    2
1.000000e+11    2
2.008236e+07    1
               ..
9.939535e+09    1
1.000000e+08    1
3.806569e+10    1
1.065179e+11    1
5.484531e+08    1
Name: count, Length: 91, dtype: int64
zero values= 0
Negative values:  0
Infinite value: 0
unique: [2.00823650e+07 1.22035557e+08 1.88927789e+11 1.33161220e+08
 9.99856277e+10 7.43312567e+10 6.33830911e+08 9.49433893e+10
 2.23790277e+10 1.69248392e+07 9.55307079e+08 1.71569863e+11
 1.14240853e+12 9.83869129e+09 1.88028339e+07 2.93532015e+08
 1.00000000e+09 9.85239504e+08 4.50000000e+10 5.00017868e+10
 2.00875405e+07 4.58693959e+09 4.50176826e+09 4.28021988e+09
 7.75946481e+07 3.95660019e+10 5.24664634e+09 8.90460420e+08
 3.31219461e+09 5.00000000e+10 4.63441061e+08 1.30594237e+09
 1.00000000e+10 5.89496239e+14 2.79811072e+09 2.79706320e+09
 9.89126193e+10 5.41258479e+09 7.07747089e+05 2.30910030e+09
 2.42130713e+09 2.10000000e+07 1.93612077e+09 6.21931679e+09
 7.80396812e+09 4.32503322e+05 1.60000000e+07 1.70211794e+09
 1.00000000e+11 8.34788573e+11 5.56269826e+08 8.98232729e+14
 1.49127022e+09 1.50000000e+10 4.20690000e+14 1.38294204e+09
 2.34626651e+10 9.10920875e+08 1.34447500e+09 1.32000000e+09
 1.11962533e+09 1.28150001e+09 1.58131277e+08 8.09797321e+07
 1.71410471e+10 2.76923315e+10 1.07117791e+10 9.11211100e+06
 1.18874452e+08 5.29922362e+08 1.46124930e+07 1.42155021e+08
 9.03997430e+09 7.04755042e+08 8.18874304e+09 7.26191847e+07
 6.72308859e+08 6.86148731e+09 5.33532275e+08 1.28246882e+07
 6.79991367e+08 6.99000000e+08 8.59850412e+10 3.31857365e+08
 1.95707060e+09 9.65350000e+08 9.93953491e+09 1.00000000e+08
 3.80656864e+10 1.06517930e+11 5.48453144e+08]

In [22]:
# max supply column

print("missing values  ",df["Max_Supply"].isnull().sum())
print("Duplicatedd    ",df["Max_Supply"].duplicated().sum())
print("Value counts  ",df["Max_Supply"].value_counts())

print("zero values=",(df["Max_Supply"]==0).sum())

# fill missing values
df["Max_Supply"]=df["Max_Supply"].fillna(df["Max_Supply"].median())
print(df["Max_Supply"])

print("Negative values: ",(df["Max_Supply"]< 0).sum())

missing values   49
Duplicatedd     70
Value counts   Max_Supply
1.000000e+10    8
1.000000e+09    7
2.100000e+07    5
1.000000e+11    5
4.000000e+08    2
2.000000e+08    1
1.150000e+12    1
4.500000e+10    1
8.400000e+07    1
5.000000e+10    1
7.200000e+08    1
6.219317e+09    1
8.000000e+09    1
1.600000e+07    1
2.100000e+09    1
1.000000e+12    1
9.999900e+14    1
1.500000e+10    1
4.206900e+14    1
2.346267e+10    1
2.000000e+09    1
2.107000e+08    1
2.870403e+10    1
1.426228e+08    1
1.461249e+07    1
9.900000e+09    1
6.442451e+08    1
1.892000e+07    1
8.671263e+10    1
Name: count, dtype: int64
zero values= 0
0     2.100000e+07
1     6.219317e+09
2     6.219317e+09
3     2.000000e+08
4     1.000000e+11
          ...
95    6.219317e+09
96    6.219317e+09
97    6.219317e+09
98    6.219317e+09
99    6.219317e+09
Name: Max_Supply, Length: 100, dtype: float64
Negative values:  0

In [23]:
# Ath column

print("missing values  ",df["Ath"].isnull().sum())
print("Duplicatedd    ",df["Ath"].duplicated().sum())
print("Value counts  ",df["Ath"].value_counts())

print("zero values=",(df["Ath"]==0).sum())
print("Negative values: ",(df["Ath"]< 0).sum())

missing values   0
Duplicatedd     1
Value counts   Ath
1.260000         2
126080.000000    1
4946.050000      1
1.320000         1
1369.990000      1
                ..
0.450785         1
52.620000        1
0.192754         1
0.150073         1
1.330000         1
Name: count, Length: 99, dtype: int64
zero values= 0
Negative values:  0

In [24]:
# Ath_Change_Percentage column

print("missing values  ",df["Ath_Change_Percentage"].isnull().sum())
print("Duplicatedd    ",df["Ath_Change_Percentage"].duplicated().sum())
print("Value counts  ",df["Ath_Change_Percentage"].value_counts())

print("zero values=",(df["Ath_Change_Percentage"]==0).sum())
print("Negative values: ",(df["Ath_Change_Percentage"]< 0).sum())

missing values   0
Duplicatedd     5
Value counts   Ath_Change_Percentage
 0.00000     6
-39.03115    1
-51.11726    1
-24.44314    1
-48.42904    1
            ..
-82.94928    1
-88.72517    1
-85.41580    1
-95.77151    1
-24.78136    1
Name: count, Length: 95, dtype: int64
zero values= 6
Negative values:  94

In [25]:
# Ath_Date column

print("missing values  ",df["Ath_Date"].isnull().sum())
print("Duplicatedd    ",df["Ath_Date"].duplicated().sum())
print("Value counts  ",df["Ath_Date"].value_counts())

df["Ath_Date"]=pd.to_datetime(df["Ath_Date"],errors="coerce")

print("unique:",df['Ath_Date'])

df["Ath_Date"]=df["Ath_Date"].astype(str).str.strip()

missing values   0
Duplicatedd     2
Value counts   Ath_Date
2017-12-19T16:00:00.000Z    2
2026-09-10T13:25:00.000Z    2
2025-10-06T10:57:42.000Z    1
2025-08-24T11:21:03.000Z    1
2018-07-23T16:00:00.000Z    1
                           ..
2018-12-16T16:00:00.000Z    1
2024-03-14T07:06:22.000Z    1
2021-08-20T20:39:48.000Z    1
2023-01-09T19:14:05.000Z    1
2024-07-12T00:28:59.000Z    1
Name: count, Length: 98, dtype: int64
unique: 0    2025-10-06 10:57:42+00:00
1    2025-08-24 11:21:03+00:00
2    2018-07-23 16:00:00+00:00
3    2025-10-13 00:41:24+00:00
4    2025-07-17 19:40:53+00:00
                ...
95   2018-12-16 16:00:00+00:00
96   2024-03-14 07:06:22+00:00
97   2021-08-20 20:39:48+00:00
98   2023-01-09 19:14:05+00:00
99   2024-07-12 00:28:59+00:00
Name: Ath_Date, Length: 100, dtype: datetime64[us, UTC]

In [26]:
# Atlcolumn


print("missing values  ",df["Atl"].isnull().sum())
print("Duplicatedd    ",df["Atl"].duplicated().sum())
print("Value counts  ",df["Atl"].value_counts())

print("zero values=",(df["Atl"]==0).sum())
print("Negative values: ",(df["Atl"]< 0).sum())

missing values   0
Duplicatedd     1
Value counts   Atl
1.150000     2
67.810000    1
0.432979     1
0.572521     1
0.039818     1
            ..
0.000275     1
0.657401     1
0.000395     1
0.005860     1
0.962885     1
Name: count, Length: 99, dtype: int64
zero values= 0
Negative values:  0

In [27]:
# Atl_Change_Percentage column

print("missing values  ",df["Atl_Change_Percentage"].isnull().sum())
print("Duplicatedd    ",df["Atl_Change_Percentage"].duplicated().sum())
print("Value counts  ",df["Atl_Change_Percentage"].value_counts())

print("zero values=",(df["Atl_Change_Percentage"]==0).sum())
print("Negative values: ",(df["Atl_Change_Percentage"]< 0).sum())

missing values   0
Duplicatedd     0
Value counts   Atl_Change_Percentage
1.132617e+05    1
5.583024e+05    1
7.461181e+01    1
1.774281e+06    1
5.038666e+04    1
               ..
2.783099e+04    1
8.024772e+02    1
7.011147e+03    1
8.282510e+00    1
3.561000e+00    1
Name: count, Length: 100, dtype: int64
zero values= 1
Negative values:  0

In [28]:
#Atl_Datecolumn

print("missing values  ",df["Atl_Date"].isnull().sum())
print("Duplicatedd    ",df["Atl_Date"].duplicated().sum())
print("Value counts  ",df["Atl_Date"].value_counts())

df["Atl_Date"]=pd.to_datetime(df["Atl_Date"],errors="coerce")

print("unique:",df['Atl_Date'])

df["Atl_Date"]=df["Atl_Date"].astype(str).str.strip()

missing values   0
Duplicatedd     1
Value counts   Atl_Date
2015-01-13T16:00:00.000Z    2
2013-07-05T16:00:00.000Z    1
2015-10-19T16:00:00.000Z    1
2015-03-01T16:00:00.000Z    1
2017-10-18T16:00:00.000Z    1
                           ..
2019-11-01T03:05:12.000Z    1
2020-11-03T08:19:30.000Z    1
2019-07-21T16:00:00.000Z    1
2026-08-19T10:09:30.000Z    1
2025-04-10T00:30:51.000Z    1
Name: count, Length: 99, dtype: int64
unique: 0    2013-07-05 16:00:00+00:00
1    2015-10-19 16:00:00+00:00
2    2015-03-01 16:00:00+00:00
3    2017-10-18 16:00:00+00:00
4    2014-05-21 16:00:00+00:00
                ...
95   2019-11-01 03:05:12+00:00
96   2020-11-03 08:19:30+00:00
97   2019-07-21 16:00:00+00:00
98   2026-08-19 10:09:30+00:00
99   2025-04-10 00:30:51+00:00
Name: Atl_Date, Length: 100, dtype: datetime64[us, UTC]

In [29]:
# Roi column
df.drop('Roi', axis=1, inplace=True)

In [30]:
# Last_Updated column

print("missing values  ",df["Ath_Change_Percentage"].isnull().sum())
print("Duplicatedd    ",df["Ath_Change_Percentage"].duplicated().sum())
print("Value counts  ",df["Ath_Change_Percentage"].value_counts())


print("zero value:", (df['Last_Updated'] == 0).sum())
print("-"*50)

print("unique values:", df['Last_Updated'].nunique())

missing values   0
Duplicatedd     5
Value counts   Ath_Change_Percentage
 0.00000     6
-39.03115    1
-51.11726    1
-24.44314    1
-48.42904    1
            ..
-82.94928    1
-88.72517    1
-85.41580    1
-95.77151    1
-24.78136    1
Name: count, Length: 95, dtype: int64
zero value: 0
--------------------------------------------------
unique values: 1

In [31]:
df.columns

Index(['Unnamed: 0', 'Id', 'Symbol', 'Name', 'Image', 'Current_Price',
       'Market_Cap', 'Market_Cap_Rank', 'Fully_Diluted_Valuation',
       'Total_Volume', 'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Last_Updated'],
      dtype='str')

In [32]:
df

,Unnamed: 0,Id,Symbol,Name,Image,Current_Price,Market_Cap,Market_Cap_Rank,Fully_Diluted_Valuation,Total_Volume,...,Circulating_Supply,Total_Supply,Max_Supply,Ath,Ath_Change_Percentage,Ath_Date,Atl,Atl_Change_Percentage,Atl_Date,Last_Updated
0,0,Bitcoin,Btc,Bitcoin,[https://coin-images.coingecko.com/coins/image...,76869.000000,1543780270779,1,1543789572409,3.415245e+10,...,2.008222e+07,2.008236e+07,2.100000e+07,126080.000000,-39.03115,2025-10-06 10:57:42+00:00,67.810000,1.132617e+05,2013-07-05 16:00:00+00:00,2026-09-10T13:27:20.000Z
1,1,Ethereum,Eth,Ethereum,[https://coin-images.coingecko.com/coins/image...,2417.760000,295019194043,2,295019194043,1.358600e+10,...,1.220356e+08,1.220356e+08,6.219317e+09,4946.050000,-51.11726,2025-08-24 11:21:03+00:00,0.432979,5.583024e+05,2015-10-19 16:00:00+00:00,2026-09-10T13:27:20.000Z
2,2,Tether,Usdt,Tether,[https://coin-images.coingecko.com/coins/image...,0.999689,183399747382,3,188864872668,5.765036e+10,...,1.834608e+11,1.889278e+11,6.219317e+09,1.320000,-24.44314,2018-07-23 16:00:00+00:00,0.572521,7.461181e+01,2015-03-01 16:00:00+00:00,2026-09-10T13:27:20.000Z
3,3,Binancecoin,Bnb,Bnb,[https://coin-images.coingecko.com/coins/image...,706.520000,94081938222,4,94081937558,1.262140e+09,...,1.331612e+08,1.331612e+08,2.000000e+08,1369.990000,-48.42904,2025-10-13 00:41:24+00:00,0.039818,1.774281e+06,2017-10-18 16:00:00+00:00,2026-09-10T13:27:20.000Z
4,4,Ripple,Xrp,Xrp,[https://coin-images.coingecko.com/coins/image...,1.360000,85090865143,5,135595357428,2.406497e+09,...,6.274450e+10,9.998563e+10,1.000000e+11,3.650000,-62.80759,2025-07-17 19:40:53+00:00,0.002686,5.038666e+04,2014-05-21 16:00:00+00:00,2026-09-10T13:27:20.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,Beldex,Bdx,Beldex,[https://coin-images.coingecko.com/coins/image...,0.076862,604714731,96,763675850,1.169582e+07,...,7.870595e+09,9.939535e+09,6.219317e+09,0.450785,-82.94928,2018-12-16 16:00:00+00:00,0.000275,2.783099e+04,2019-11-01 03:05:12+00:00,2026-09-10T13:27:20.000Z
96,96,Injective-Protocol,Inj,Injective,[https://coin-images.coingecko.com/coins/image...,5.930000,593229023,97,593229023,8.349674e+07,...,1.000000e+08,1.000000e+08,6.219317e+09,52.620000,-88.72517,2024-03-14 07:06:22+00:00,0.657401,8.024772e+02,2020-11-03 08:19:30+00:00,2026-09-10T13:27:20.000Z
97,97,Xdce-Crowd-Sale,Xdc,Xdc Network,[https://coin-images.coingecko.com/coins/image...,0.028112,560726767,98,1070074832,5.787636e+06,...,1.994669e+10,3.806569e+10,6.219317e+09,0.192754,-85.41580,2021-08-20 20:39:48+00:00,0.000395,7.011147e+03,2019-07-21 16:00:00+00:00,2026-09-10T13:27:20.000Z
98,98,Flare-Networks,Flr,Flare,[https://coin-images.coingecko.com/coins/image...,0.006346,551497765,99,675979791,3.149003e+06,...,8.690260e+10,1.065179e+11,6.219317e+09,0.150073,-95.77151,2023-01-09 19:14:05+00:00,0.005860,8.282510e+00,2026-08-19 10:09:30+00:00,2026-09-10T13:27:20.000Z
99,99,Usual-Usd,Usd0,Usual Usd,[https://coin-images.coingecko.com/coins/image...,0.997173,546890845,100,546890845,2.004420e+05,...,5.484531e+08,5.484531e+08,6.219317e+09,1.330000,-24.78136,2024-07-12 00:28:59+00:00,0.962885,3.561000e+00,2025-04-10 00:30:51+00:00,2026-09-10T13:27:20.000Z

In [33]:
df.to_csv("cleaned_coin_dataset.csv")